pipeline {
    agent any
    
       stage("Build") {
      

            steps {
                echo 'Building...'
                
                }
            }

    

        stage("Test") {
      

            steps {
                echo 'Testing...'
                clean test -Dcucumber.features=src/test/resources/features -Dcucumber.glue=bdd.automation.api.steps -Dtest=bdd.automation.api.runners.CucumberTestRunner





                
                }
            }
        
    
}

       
    

   
